### PR TITLE
Install USWDS 2.0

### PR DESCRIPTION
**Pull request by alexsoble**
# Notes

+ Install U.S. Web Design System Drupal project: https://www.drupal.org/project/uswds
+ Add documentation to README on how to customize CSS
+ Lots and lots of styling needed; this is a USWDS 2.0 starting point

# Screenshots

## Form

uswds-2-form

## Default Drupal homepage

uswds-2-mainpage

# Review notes

+ Import YML configuration (`drush cim`) to set the new theme locally

### CODE REVIEW

**Comment by alexsoble** [comment]
To enable and use the `crt_portal_subtheme` locally, you will need to use the following commands:

```
drush then crt_portal_subtheme
drush config-set system.theme default crt_portal_subtheme
```

**Comment by alexsoble** [comment]
☝️ I just exported and committed the theme config as YML, so now as I understand it a local `drush cim` should import the new USWDS 2.0 theme.

**Comment by LindsayYoung** [comment]
It looks like the usa-form class is what restricts the width on the page. Maybe you already knew that, but I wanted to document it for later.

**Comment by alexsoble** [comment]
@LindsayYoung Yep, saw that!

**Comment by alexsoble** [comment]
@LindsayYoung Figured out that to apply USWDS theme settings, I have to apply them to the CRT Portal Subtheme rather than the base theme. This change is committed in 7c8557a83260539c819876d856db7db595697f70; if you run a fresh `drush cim` followed by `drush cr` you should see the USWDS gov banner enabled locally.

**Comment by LindsayYoung** [comment]
I did a little reading for the pr review that I thought was helpful so I'm documenting it here. 

Drupal pre-process hooks prepare variables for theme templates. The HTML is rendered from an array that results from preprocessing. 

https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/group/themeable/8.2.x

**Comment by alexsoble** [comment]
@LindsayYoung Thank you and thank you for sharing that documentation on preprocessing!

**Pull request merged**
